### ISSUE TITLE
Heavy does not concatinate inputs in message boxes

### ISSUE THREAD

**Issue by mhroth** [enzienaudio/heavy#31]
```
#N canvas 365 249 286 155 10;
#X obj 15 10 loadbang;
#X obj 15 51 f 3;
#X obj 23 30 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144 -1
-1;
#X msg 15 75 hello-\$1;
#X obj 15 99 print;
#X text 13 120 hello-3 is expected. Heavy returns hello-\$1;
#X connect 0 0 1 0;
#X connect 1 0 3 0;
#X connect 2 0 1 0;
#X connect 3 0 4 0;
```

**Comment by ylevtov** [comment]
Even the following patch (or any larger patch containing any message box with $1-string) causes a fatal error for the compiler...

```
#N canvas 693 93 681 729 10;
#X msg 348 362 \$1-a;
```

**Comment by ylevtov** [comment]
_Bump_

(I thought this one had been fixed?)

**Comment by ylevtov** [comment]
_Re-bump_

Even just some more descriptive error reporting would be a huge help. Was currently just getting

```
Traceback (most recent call last):
  File "uploader.py", line 276, in <module>
    main()
  File "uploader.py", line 218, in main
    for x in r_json["warnings"]:
KeyError: 'warnings'
```

**Comment by ylevtov** [comment]
Re-bump. This is cropping up again and again for me. Any idea where this is on the roadmap?
