### ISSUE TITLE
heavy uploader fails without meaningful error

### ISSUE THREAD

**Issue by giuliomoro** [enzienaudio/heavy#95]
In the uploaded patch, I am trying to [tabread4~] from an array that is not existing.
The uploader.py (latest rev) fails with no meaningful warning.
Expected behaviour: it should detect and report the error back to the client

Here is the traceback

```
Traceback (most recent call last):
  File "hvresources/uploader.py", line 324, in <module>
    main()
  File "hvresources/uploader.py", line 271, in main
    file_url = __get_file_url_for_generator(reply_json, g)
  File "hvresources/uploader.py", line 316, in __get_file_url_for_generator
    for i in json_api["included"]:
KeyError: 'included'
error
```

**Comment by mhroth** [comment]
Fixed as of release ``r2016.07.05`.
